#!/usr/bin/env bash
# protocol-zero.sh
# Protocol Zero — AI Attribution Scanner for Cadence Cycle Tracker
#
# Scans source files and commit messages for forbidden AI attribution markers.
# Hard-exempt paths: docs/, .claude/, CLAUDE.md — never scanned under any condition.
#
# Usage:
#   ./scripts/protocol-zero.sh                         Scan entire codebase
#   ./scripts/protocol-zero.sh --dir <path>            Scan specific directory
#   ./scripts/protocol-zero.sh --commit-msg "message"  Validate commit message
#   ./scripts/protocol-zero.sh --commit-msg-file path  Validate from file
#   ./scripts/protocol-zero.sh --help                  Usage
#
# Exit codes:
#   0  Clean — no violations detected
#   1  Violation(s) detected

set -euo pipefail

# ---------------------------------------------------------------------------
# ANSI color codes (using $'...' ANSI C quoting so printf works without -e)
# ---------------------------------------------------------------------------
RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
YELLOW=$'\033[0;33m'
CYAN=$'\033[0;36m'
BOLD=$'\033[1m'
DIM=$'\033[2m'
NC=$'\033[0m'

# ---------------------------------------------------------------------------
# Prohibited patterns — case-insensitive
# Matches AI attribution artifacts forbidden by Protocol Zero
# ---------------------------------------------------------------------------
PROHIBITED_PATTERNS=(
    "generated by claude"
    "generated by ai"
    "generated by copilot"
    "generated by gpt"
    "generated by chatgpt"
    "generated by llm"
    "ai\.assisted"
    "ai-assisted"
    "ai assisted"
    "ai generated"
    "ai-generated"
    "created with ai"
    "created by ai"
    "written by ai"
    "written by claude"
    "co-authored-by:.*claude"
    "co-authored-by:.*copilot"
    "co-authored-by:.*ai"
    "co-authored-by:.*anthropic"
    "co-authored-by:.*openai"
    "i hope this helps"
    "as requested"
    "here is the code"
    "as an ai"
    "as a language model"
    "i'm an ai"
    "i am an ai"
    "\bllm\b"
)

# ---------------------------------------------------------------------------
# Hard-exempt paths — NEVER scanned, regardless of any other configuration.
# docs/ and .claude/ contain governance and skill files that legitimately
# reference prohibited patterns as examples or configuration.
# ---------------------------------------------------------------------------
HARD_EXEMPT_DIRS=(
    "docs"
    ".claude"
)

HARD_EXEMPT_FILES=(
    "CLAUDE.md"
    "protocol-zero.sh"
    "settings.local.json"
    "MEMORY.md"
)

# ---------------------------------------------------------------------------
# Directory exclusions — applied via grep --exclude-dir and find -prune.
# Covers iOS/Xcode toolchain and common build artifact directories.
# docs and .claude appear here AND in HARD_EXEMPT_DIRS (belt-and-suspenders).
# ---------------------------------------------------------------------------
EXCLUDE_DIRS=(
    ".git"
    ".claude"
    "docs"
    "build"
    "DerivedData"
    "xcuserdata"
    ".swiftpm"
    ".build"
    "node_modules"
    "vendor"
    "Pods"
)

# ---------------------------------------------------------------------------
# Binary file extensions — skipped during scan
# Covers iOS build artifacts, media, fonts, and asset catalog binaries
# ---------------------------------------------------------------------------
BINARY_EXTENSIONS=(
    "png" "jpg" "jpeg" "gif" "ico" "svg" "webp"
    "woff" "woff2" "ttf" "eot" "otf"
    "pdf" "zip" "tar" "gz" "bz2"
    "mp3" "mp4" "wav" "avi" "mov"
    "m4a" "aac"
    "ipa" "car" "mobileprovision"
    "db" "db-wal" "db-shm"
    "lock" "lockb"
    "p8"
    "skill"
    "xcframework"
)

# ---------------------------------------------------------------------------
# Violation tracking
# ---------------------------------------------------------------------------
VIOLATIONS_FOUND=0
VIOLATION_RECORDS=()   # Each element: "filepath|line_num|pattern"

# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------
print_banner() {
    printf '\n'
    printf '%s%s\n' "$BOLD" '══════════════════════════════════════════════════════════════'
    printf '%s  Protocol Zero  —  AI Attribution Scanner  [Cadence]%s\n' "$BOLD" "$NC"
    printf '%s%s%s\n' "$BOLD" '══════════════════════════════════════════════════════════════' "$NC"
    printf '\n'
}

print_section() {
    printf '%s%s─── %s %s\n' "$CYAN" "$BOLD" "$1" "$NC"
    printf '\n'
}

print_pass() {
    printf '  %s%s[PASS]%s  %s\n' "$GREEN" "$BOLD" "$NC" "$1"
}

print_fail() {
    printf '  %s%s[FAIL]%s  %s\n' "$RED" "$BOLD" "$NC" "$1"
}

print_info() {
    printf '  %s[INFO]%s  %s\n' "$DIM" "$NC" "$1"
}

# ---------------------------------------------------------------------------
# Build grep exclusion flag arrays.
# Returns one flag per line for safe array reconstruction by the caller.
# ---------------------------------------------------------------------------
build_grep_exclude_args() {
    for dir in "${EXCLUDE_DIRS[@]}"; do
        printf '%s\n' "--exclude-dir=${dir}"
    done
    for ext in "${BINARY_EXTENSIONS[@]}"; do
        printf '%s\n' "--exclude=*.${ext}"
    done
    for file in "${HARD_EXEMPT_FILES[@]}"; do
        printf '%s\n' "--exclude=${file}"
    done
}

# ---------------------------------------------------------------------------
# Check whether a resolved file path is hard-exempt.
# Applied as a secondary guard after grep exclusions.
# ---------------------------------------------------------------------------
is_hard_exempt() {
    local filepath="$1"
    local filename
    filename=$(basename "$filepath")

    for exempt_file in "${HARD_EXEMPT_FILES[@]}"; do
        if [[ "$filename" == "$exempt_file" ]]; then
            return 0
        fi
    done

    for exempt_dir in "${HARD_EXEMPT_DIRS[@]}"; do
        if [[ "$filepath" == *"/${exempt_dir}/"* || "$filepath" == "${exempt_dir}/"* ]]; then
            return 0
        fi
    done

    return 1
}

# ---------------------------------------------------------------------------
# Count scannable files in a directory tree.
# Mirrors grep exclusion logic using find -prune for directory exclusion.
# ---------------------------------------------------------------------------
count_scannable_files() {
    local root_dir="$1"

    find "$root_dir" \
        -name ".git"          -prune -o \
        -name ".claude"       -prune -o \
        -name "docs"          -prune -o \
        -name "build"         -prune -o \
        -name "DerivedData"   -prune -o \
        -name "xcuserdata"    -prune -o \
        -name ".swiftpm"      -prune -o \
        -name ".build"        -prune -o \
        -name "node_modules"  -prune -o \
        -type f \
        ! -name "*.png"   ! -name "*.jpg"  ! -name "*.jpeg" ! -name "*.gif" \
        ! -name "*.ico"   ! -name "*.svg"  ! -name "*.webp" \
        ! -name "*.woff"  ! -name "*.woff2" ! -name "*.ttf" ! -name "*.otf" \
        ! -name "*.pdf"   ! -name "*.zip"  ! -name "*.tar"  ! -name "*.gz" \
        ! -name "*.mp3"   ! -name "*.mp4"  ! -name "*.wav" \
        ! -name "*.m4a"   ! -name "*.aac" \
        ! -name "*.ipa"   ! -name "*.car"  ! -name "*.mobileprovision" \
        ! -name "*.db"    ! -name "*.db-wal" ! -name "*.db-shm" \
        ! -name "*.p8"    ! -name "*.lock" ! -name "*.lockb" \
        ! -name "*.skill" ! -name "*.xcframework" \
        -print 2>/dev/null \
    | wc -l \
    | tr -d ' '
}

# ---------------------------------------------------------------------------
# Print violations as an aligned table.
# Columns: FILE (45), LINE (5), PATTERN (30), SEVERITY
# ---------------------------------------------------------------------------
print_violations_table() {
    if [[ ${#VIOLATION_RECORDS[@]} -eq 0 ]]; then
        return
    fi

    local COL_FILE=45
    local COL_LINE=5
    local COL_PATTERN=30

    local sep_file sep_line sep_pattern
    sep_file=$(printf '%0.s─' {1..45})
    sep_line=$(printf '%0.s─' {1..5})
    sep_pattern=$(printf '%0.s─' {1..30})

    printf '\n'
    printf '  %s%-*s  %-*s  %-*s  %s%s\n' \
        "$BOLD" \
        "$COL_FILE" "FILE" \
        "$COL_LINE" "LINE" \
        "$COL_PATTERN" "PATTERN" \
        "SEVERITY" \
        "$NC"
    printf '  %s%-*s  %-*s  %-*s  %s%s\n' \
        "$DIM" \
        "$COL_FILE" "$sep_file" \
        "$COL_LINE" "$sep_line" \
        "$COL_PATTERN" "$sep_pattern" \
        "────────" \
        "$NC"

    for record in "${VIOLATION_RECORDS[@]}"; do
        local file line pattern
        file=$(printf '%s' "$record"    | cut -d'|' -f1)
        line=$(printf '%s' "$record"    | cut -d'|' -f2)
        pattern=$(printf '%s' "$record" | cut -d'|' -f3)

        # Truncate file path from the left if it exceeds column width
        if [[ ${#file} -gt $COL_FILE ]]; then
            file="…${file: -$((COL_FILE - 1))}"
        fi

        printf '  %s%-*s%s  %-*s  %s%-*s%s  %sCRITICAL%s\n' \
            "$RED" \
            "$COL_FILE" "$file" \
            "$NC" \
            "$COL_LINE" "$line" \
            "$YELLOW" \
            "$COL_PATTERN" "${pattern:0:$COL_PATTERN}" \
            "$NC" \
            "$RED" \
            "$NC"
    done

    printf '\n'
}

# ---------------------------------------------------------------------------
# Print the scan summary panel.
# ---------------------------------------------------------------------------
print_summary() {
    local files_scanned="$1"
    local violation_count="$2"

    printf '\n'
    printf '  %sScan Summary%s\n' "$BOLD" "$NC"
    printf '  %s%s%s\n' "$DIM" '────────────────────────────────────────────────' "$NC"
    printf '  %-24s %s\n' "Files scanned:"     "$files_scanned"
    printf '  %-24s %s\n' "Violations found:"  "$violation_count"
    printf '  %-24s %s\n' "Hard-exempt paths:" "docs/  .claude/  CLAUDE.md"
    printf '\n'

    if [[ "$violation_count" -eq 0 ]]; then
        printf '  %s%-24s%s %s%sPASS%s\n' "$BOLD" "Result:" "$NC" "$GREEN" "$BOLD" "$NC"
    else
        printf '  %s%-24s%s %s%sFAIL%s\n' "$BOLD" "Result:" "$NC" "$RED" "$BOLD" "$NC"
    fi

    printf '\n'
}

# ---------------------------------------------------------------------------
# Scan a raw text string for prohibited patterns.
# Used for commit message validation.
# ---------------------------------------------------------------------------
scan_text_for_violations() {
    local text="$1"
    local source="$2"

    for pattern in "${PROHIBITED_PATTERNS[@]}"; do
        if printf '%s' "$text" | grep -iEq "$pattern"; then
            VIOLATIONS_FOUND=1
            VIOLATION_RECORDS+=("${source}|—|${pattern}")
        fi
    done
}

# ---------------------------------------------------------------------------
# Commit message scan mode
# ---------------------------------------------------------------------------
scan_commit_message() {
    local message="$1"

    print_banner
    print_section "Commit Message Validation"
    print_info "Mode: commit message"
    printf '\n'

    scan_text_for_violations "$message" "commit-message"

    if [[ $VIOLATIONS_FOUND -eq 1 ]]; then
        print_violations_table
        print_summary 1 "${#VIOLATION_RECORDS[@]}"
        print_fail "Protocol Zero violation in commit message — attribution detected."
        printf '\n'
        printf '  %s%sAction:%s Remove attribution markers before committing.\n' "$YELLOW" "$BOLD" "$NC"
        printf '\n'
        return 1
    else
        print_summary 1 0
        print_pass "Commit message is compliant."
        printf '\n'
        return 0
    fi
}

# ---------------------------------------------------------------------------
# Full codebase scan mode
# ---------------------------------------------------------------------------
scan_codebase() {
    local root_dir="${1:-.}"

    print_banner
    print_section "Codebase Scan"
    print_info "Root:         ${root_dir}"
    print_info "Hard-exempt:  docs/  .claude/  CLAUDE.md"
    printf '\n'

    # Build grep exclusion flags into an array
    local grep_exclude_args=()
    while IFS= read -r arg; do
        grep_exclude_args+=("$arg")
    done < <(build_grep_exclude_args)

    for pattern in "${PROHIBITED_PATTERNS[@]}"; do
        local matching_files
        # grep -ril: recursive, case-insensitive, filenames only
        # || true prevents set -e from aborting when grep finds no matches
        matching_files=$(grep -rilE "${grep_exclude_args[@]}" "$pattern" "$root_dir" 2>/dev/null || true)

        [[ -z "$matching_files" ]] && continue

        while IFS= read -r filepath; do
            # Secondary hard-exempt check (belt-and-suspenders over grep exclusions)
            if is_hard_exempt "$filepath"; then
                continue
            fi

            local line_matches
            line_matches=$(grep -inE "$pattern" "$filepath" 2>/dev/null || true)

            [[ -z "$line_matches" ]] && continue

            VIOLATIONS_FOUND=1

            while IFS= read -r line_match; do
                local line_num
                line_num=$(printf '%s' "$line_match" | cut -d: -f1)
                VIOLATION_RECORDS+=("${filepath}|${line_num}|${pattern}")
            done <<< "$line_matches"

        done <<< "$matching_files"
    done

    local files_scanned
    files_scanned=$(count_scannable_files "$root_dir")

    if [[ $VIOLATIONS_FOUND -eq 1 ]]; then
        print_violations_table
        print_summary "$files_scanned" "${#VIOLATION_RECORDS[@]}"
        print_fail "Protocol Zero violation(s) detected — attribution artifacts found."
        printf '\n'
        printf '  %s%sAction:%s Remove all attribution artifacts before proceeding.\n' "$YELLOW" "$BOLD" "$NC"
        printf '\n'
        return 1
    else
        print_summary "$files_scanned" 0
        print_pass "No attribution artifacts detected."
        printf '\n'
        return 0
    fi
}

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
main() {
    local mode="codebase"
    local commit_msg=""
    local commit_msg_file=""
    local scan_dir="."

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --commit-msg)
                mode="commit"
                commit_msg="$2"
                shift 2
                ;;
            --commit-msg-file)
                mode="commit-file"
                commit_msg_file="$2"
                shift 2
                ;;
            --dir)
                scan_dir="$2"
                shift 2
                ;;
            --help|-h)
                printf 'Protocol Zero — AI Attribution Scanner\n\n'
                printf 'Usage:\n'
                printf '  %s                              Scan entire codebase\n'  "$0"
                printf '  %s --dir <path>                 Scan specific directory\n' "$0"
                printf '  %s --commit-msg "message"       Validate commit message\n' "$0"
                printf '  %s --commit-msg-file <path>     Validate from file\n' "$0"
                printf '\nExit codes:\n'
                printf '  0  No violations\n'
                printf '  1  Violation(s) detected\n'
                exit 0
                ;;
            *)
                printf 'Unknown argument: %s\n' "$1" >&2
                shift
                ;;
        esac
    done

    case "$mode" in
        commit)
            scan_commit_message "$commit_msg"
            ;;
        commit-file)
            if [[ ! -f "$commit_msg_file" ]]; then
                printf 'Error: commit message file not found: %s\n' "$commit_msg_file" >&2
                exit 1
            fi
            local msg
            msg=$(cat "$commit_msg_file")
            scan_commit_message "$msg"
            ;;
        codebase)
            scan_codebase "$scan_dir"
            ;;
    esac
}

main "$@"
